- name: Deploy Docker Container
  hosts: web
  become: true
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, python3-pip]
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Pull the Docker image
      docker_image:
        name: atharvab3/myapp:0ddf56c
        source: pull

    - name: Run the Docker container (map port 80→3000)
      docker_container:
        name: node_app
        image: atharvab3/myapp:0ddf56c
        state: started
        restart_policy: always
        published_ports:
          - "80:3000"
